version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kafka-network

  webserver:
    build:
      context: ./airflow
    restart: always
    depends_on:
      - postgres
    environment:
      LOAD_EX: n
      EXECUTOR: Local
    volumes:
      - ./dags:/usr/local/airflow/dags
    ports:
      - 8080:8080
    command: webserver
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "[ -f /usr/local/airflow/airflow-webserver.pid ]"
        ]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - kafka-network

volumes:
  postgres_data:


networks:
  kafka-network:
